# whitelist
branches:
  only:
    - master
    - /^tickets\/.*$/

sudo: false

services:
  - docker

language: c++

before_install:
  - docker pull qserv/qserv:dev
  - cp ./admin/tools/docker/deployment/travis/env.sh ./admin/tools/docker/deployment/localhost/env.sh

script:
  - ./admin/tools/docker/3_build-git-image.sh -L -T travis -S "$PWD"
  - ./admin/tools/docker/4_build-configured-images.sh -L -i travis
  - ./admin/tools/docker/deployment/localhost/run-multinode-tests.sh
